name: Node.js Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
        # Defaults to the user or organization that owns the workflow file
        scope: '@happysanta'
    - run: yarn
    - run: yarn run lint-check && yarn run test
    - run: yarn run build
    - run: yarn publish --no-git-tag-version --access public --new-version $(git describe --tags)
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
